# Generated by Django 4.0.4 on 2022-05-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon_name', models.CharField(default="Hack'2x", max_length=35)),
                ('status', models.CharField(choices=[('Not Decided', 'Not Decided'), ('Winner', 'Winner'), ('Runner Up', 'Runner Up'), ('Track Winner', 'Track Winner')], default='Not Decided', max_length=12)),
                ('team', models.ManyToManyField(to='member.member')),
            ],
        ),
    ]
