# Generated by Django 4.0.4 on 2022-05-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['hackathon_name']},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='team',
        ),
    ]
