# Generated by Django 4.0.4 on 2022-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_alter_achievement_options_remove_achievement_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='hackathon_name',
            field=models.CharField(default="Hack'2x", max_length=35),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='status',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('N/A', 'N/A')], default='N/A', max_length=5),
        ),
    ]
