# Generated by Django 4.0.4 on 2022-05-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('achievement', '0003_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='team',
            field=models.ManyToManyField(to='member.member'),
        ),
    ]
